services:
  mongoexpress:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo,mongo1,mongo2
      - ME_CONFIG_MONGODB_URL="mongodb://mongo:27017,mongo1:27017,mongo2:27017/?replicaSet=rs0"
      # Add your user credentials for authentication
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=writeUser
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=secret

  # mongo0:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27337:27017
  #   volumes:
  #     - /mnt/sda1/data/mongo:/data/db

  mongo:
    hostname: mongo
    image: mongo
    command: --replSet rs0
    # healthcheck:
    #   test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0', members:[{_id:0, host:'mongo:27338', priority:1}, {_id:1, host:'mongo1:27339', priority:0.5}, {_id:2, host:'mongo2:27340', priority:0.5}]}) }" | mongosh --port 27338 --quiet
    #   interval: 5s
    #   timeout: 30s
    #   start_period: 0s
    #   start_interval: 1s
    #   retries: 30
    restart: on-failure
    volumes:
      - ~/data/mongo/db:/data/db
      - ~/data/mongo/configdb:/data/configdb

  mongo1:
    hostname: mongo1
    image: mongo
    command: --replSet rs0
    restart: on-failure
    volumes:
      - ~/data/mongo1/db:/data/db
      - ~/data/mongo1/configdb:/data/configdb

  mongo2:
    hostname: mongo2
    image: mongo
    command: --replSet rs0
    restart: on-failure
    volumes:
      - ~/data/mongo2/db:/data/db
      - ~/data/mongo2/configdb:/data/configdb