services:
  api:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/app
    depends_on:
      - weaviate
      - mongo

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/etc/mongo

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always
    env_file:
      - .env
    depends_on:
      - i2v-neural
  
  i2v-neural:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    restart: always
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 4
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["compute"]

volumes:
  weaviate_data:
  mongo_data: