services:
  api:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    labels:
      autoheal-app: true
    healthcheck:
      test: curl --fail http://api:8080/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27337:27017
    volumes:
      - ./data/mongo:/data/db

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    restart: always
    env_file:
      - .env
  
  i2v-neural:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    restart: always
    env_file:
      - .env

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal-app
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
