services:
  api:
    build:
      context: .
    command: uvicorn main:app --port 8080 --host=0.0.0.0 --use-colors --reload
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  i2v:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    restart: always
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/mongo:/data/db

  mongoexpress:
    hostname: mongoexpress
    image: mongo-express
    restart: always
    ports:
      - 8337:8081
    env_file:
      - .env

  weaviate:
    hostname: weaviate
    command: --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.3
    volumes:
      - ./data/weaviate:/var/lib/weaviate
    restart: always
    env_file:
      - .env