services:
  mongo:
    image: mongo
    command: mongod --replSet rs0
    restart: always
    env_file:
      - .env
    ports:
      - 27337:27017
    volumes:
      - ~/data/mongo:/data/db
      - ~/data/mongo_config:/data/configdb

  mongo1:
    image: mongo
    command: mongod --replSet rs0
    restart: always
    env_file:
      - .env
    volumes:
      - ~/data/mongo1:/data/db
      - ~/data/mongo1_config:/data/configdb

  mongo2:
    image: mongo
    command: mongod --replSet rs0
    restart: always
    env_file:
      - .env
    volumes:
      - ~/data/mongo2:/data/db
      - ~/data/mongo2_config:/data/configdb