services:
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    deploy:
      resources:
        limits:
          memory: 2G
    depends_on:
      - api

  api:
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /mnt/sda1:/mnt/sda1
    deploy:
      mode: replicated
      replicas: 20
      resources:
        limits:
          memory: 2G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
  
  i2v-neural:
    build:
      context: ./i2v
    restart: always
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 20
      resources:
        limits:
          memory: 2G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["compute"]

  # MONGO CLUSTER
  mongoexpress:
    image: mongo-express
    restart: always
    ports:
      - 8337:8081
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 2G

  mongo:
    hostname: mongo
    image: mongo
    command: --replSet rs0
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ~/data/mongo/db:/data/db
      - ~/data/mongo/configdb:/data/configdb

  mongo1:
    hostname: mongo1
    image: mongo
    command: --replSet rs0
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ~/data/mongo1/db:/data/db
      - ~/data/mongo1/configdb:/data/configdb

  mongo2:
    hostname: mongo2
    image: mongo
    command: --replSet rs0
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ~/data/mongo2/db:/data/db
      - ~/data/mongo2/configdb:/data/configdb

  # WEAVIATE CLUSTER
  weaviate-node-1:
    hostname: weaviate-node-1
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.3
    restart: on-failure:0
    volumes:
      - ~/data/weaviate_node_1:/var/lib/weaviate
    env_file:
      - .env
    environment:
      - CLUSTER_HOSTNAME=node1
      - CLUSTER_GOSSIP_BIND_PORT=7100
      - CLUSTER_DATA_BIND_PORT=7101
    deploy:
      resources:
        limits:
          memory: 8G

  weaviate-node-2:
    hostname: weaviate-node-2
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    restart: on-failure:0
    volumes:
      - ~/data/weaviate_node_2:/var/lib/weaviate
    env_file:
      - .env
    environment:
      - CLUSTER_HOSTNAME=node2
      - CLUSTER_GOSSIP_BIND_PORT=7102
      - CLUSTER_DATA_BIND_PORT=7103
      - CLUSTER_JOIN=weaviate-node-1:7100
    deploy:
      resources:
        limits:
          memory: 8G

  weaviate-node-3:
    hostname: weaviate-node-3
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    restart: on-failure:0
    volumes:
      - /mnt/sda1/data/weaviate_node_3:/var/lib/weaviate
    env_file:
      - .env
    environment:
      - CLUSTER_HOSTNAME=node3
      - CLUSTER_GOSSIP_BIND_PORT=7104
      - CLUSTER_DATA_BIND_PORT=7105
      - CLUSTER_JOIN=weaviate-node-1:7100
    deploy:
      resources:
        limits:
          memory: 8G

  weaviate-node-4:
    hostname: weaviate-node-4
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    restart: on-failure:0
    volumes:
      - /mnt/sda1/data/weaviate_node_4:/var/lib/weaviate
    env_file:
      - .env
    environment:
      - CLUSTER_HOSTNAME=node4
      - CLUSTER_GOSSIP_BIND_PORT=7106
      - CLUSTER_DATA_BIND_PORT=7107
      - CLUSTER_JOIN=weaviate-node-1:7100
    deploy:
      resources:
        limits:
          memory: 8G

  weaviate-node-5:
    hostname: weaviate-node-5
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    restart: on-failure:0
    volumes:
      - /mnt/sda1/data/weaviate_node_5:/var/lib/weaviate
    env_file:
      - .env
    environment:
      - CLUSTER_HOSTNAME=node5
      - CLUSTER_GOSSIP_BIND_PORT=7108
      - CLUSTER_DATA_BIND_PORT=7109
      - CLUSTER_JOIN=weaviate-node-1:7100
    deploy:
      resources:
        limits:
          memory: 8G

  weaviate-node-6:
    hostname: weaviate-node-6
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    restart: on-failure:0
    volumes:
      - /mnt/sda1/data/weaviate_node_6:/var/lib/weaviate
    env_file:
      - .env
    environment:
      - CLUSTER_HOSTNAME=node6
      - CLUSTER_GOSSIP_BIND_PORT=7110
      - CLUSTER_DATA_BIND_PORT=7111
      - CLUSTER_JOIN=weaviate-node-1:7100
    deploy:
      resources:
        limits:
          memory: 8G

  weaviate-node-7:
    hostname: weaviate-node-7
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    restart: on-failure:0
    volumes:
      - /mnt/sda1/data/weaviate_node_7:/var/lib/weaviate
    env_file:
      - .env
    environment:
      - CLUSTER_HOSTNAME=node7
      - CLUSTER_GOSSIP_BIND_PORT=7112
      - CLUSTER_DATA_BIND_PORT=7113
      - CLUSTER_JOIN=weaviate-node-1:7100
    deploy:
      resources:
        limits:
          memory: 8G

  weaviate-node-8:
    hostname: weaviate-node-8
    init: true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    restart: on-failure:0
    volumes:
      - /mnt/sda1/data/weaviate_node_8:/var/lib/weaviate
    env_file:
      - .env
    environment:
      - CLUSTER_HOSTNAME=node8
      - CLUSTER_GOSSIP_BIND_PORT=7114
      - CLUSTER_DATA_BIND_PORT=7115
      - CLUSTER_JOIN=weaviate-node-1:7100
    deploy:
      resources:
        limits:
          memory: 8G