services:
  api:
    build:
      context: .
    restart: always
    command: uvicorn main:app --port 8081 --host=0.0.0.0 --use-colors --reload
    env_file:
      - .env
    volumes:
      - ./:/app
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    links:
      - oracle

  oracle:
    image: container-registry.oracle.com/database/free:latest
    volumes:
      - ./data/oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
    restart: unless-stopped
    env_file:
      - .env_oracle