services:
  # MONGO CLUSTER
  mongoexpress:
    hostname: mongoexpress
    image: mongo-express
    restart: always
    ports:
      - 8337:8081
    env_file:
      - .env_mongoexpress
    depends_on:
      - mongo2

  mongo:
    hostname: mongo
    image: mongo
    command: --replSet rs0
    restart: always
    env_file:
      - .env_mongo
    volumes:
      - /data/mongo/db:/data/db
      - /data/mongo/configdb:/data/configdb
    depends_on:
      - node6

  mongo1:
    hostname: mongo1
    image: mongo
    command: --replSet rs0
    restart: always
    env_file:
      - .env_mongo
    volumes:
      - /data/mongo1/db:/data/db
      - /data/mongo1/configdb:/data/configdb
    depends_on:
      - mongo

  mongo2:
    hostname: mongo2
    image: mongo
    command: --replSet rs0
    restart: always
    env_file:
      - .env_mongo
    volumes:
      - /data/mongo2/db:/data/db
      - /data/mongo2/configdb:/data/configdb
    depends_on:
      - mongo1


  nginx:
    hostname: nginx
    build:
      context: ./nginx
    restart: always
    env_file:
      - .env_nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api

  api:
    build:
      context: .
    restart: always
    env_file:
      - .env_api
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/dockerd:/usr/bin/dockerd
      - /mnt/sda1:/mnt/sda1
      - /mnt/sdb1:/mnt/sdb1
      - /mnt/sdc1:/mnt/sdc1
    deploy:
      mode: replicated
      replicas: 20
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    depends_on:
      - mongoexpress

  # task-manager:
  #   build:
  #     context: .
  #   restart: always
  #   env_file:
  #     - .env_task_manager
  #   depends_on:
  #     - mongoexpress
  
  i2v:
    hostname: i2v
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    restart: always
    env_file:
      - .env_i2v
    deploy:
      mode: replicated
      replicas: 10
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["compute"]
    depends_on:
      - node6

  # WEAVIATE CLUSTER
  node1:
    hostname: node1
    init: true
    command: --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    restart: on-failure:0
    volumes:
      - /mnt/sdc1/data/weaviate_node_1:/var/lib/weaviate
    env_file:
      - .env_weaviate
    environment:
      - CLUSTER_HOSTNAME=node1
      - CLUSTER_GOSSIP_BIND_PORT=7100
      - CLUSTER_DATA_BIND_PORT=7101
    networks:
      default:
        ipv4_address: 172.19.0.5

  node2:
    hostname: node2
    init: true
    command: --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    restart: on-failure:0
    volumes:
      - /mnt/sdc1/data/weaviate_node_2:/var/lib/weaviate
    env_file:
      - .env_weaviate
    environment:
      - CLUSTER_HOSTNAME=node2
      - CLUSTER_GOSSIP_BIND_PORT=7102
      - CLUSTER_DATA_BIND_PORT=7103
      - CLUSTER_JOIN=node1:7100
    networks:
      default:
        ipv4_address: 172.19.0.8
    depends_on:
      - node1

  node3:
    hostname: node3
    init: true
    command: --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    restart: on-failure:0
    volumes:
      - /mnt/sda1/data/weaviate_node_3:/var/lib/weaviate
    env_file:
      - .env_weaviate
    environment:
      - CLUSTER_HOSTNAME=node3
      - CLUSTER_GOSSIP_BIND_PORT=7104
      - CLUSTER_DATA_BIND_PORT=7105
      - CLUSTER_JOIN=node1:7100
    networks:
      default:
        ipv4_address: 172.19.0.10
    depends_on:
      - node2

  node4:
    hostname: node4
    init: true
    command: --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    restart: on-failure:0
    volumes:
      - /mnt/sda1/data/weaviate_node_4:/var/lib/weaviate
    env_file:
      - .env_weaviate
    environment:
      - CLUSTER_HOSTNAME=node4
      - CLUSTER_GOSSIP_BIND_PORT=7106
      - CLUSTER_DATA_BIND_PORT=7107
      - CLUSTER_JOIN=node1:7100
    networks:
      default:
        ipv4_address: 172.19.0.12
    depends_on:
      - node3

  node5:
    hostname: node5
    init: true
    command: --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    restart: on-failure:0
    volumes:
      - /mnt/sdb1/data/weaviate_node_5:/var/lib/weaviate
    env_file:
      - .env_weaviate
    environment:
      - CLUSTER_HOSTNAME=node5
      - CLUSTER_GOSSIP_BIND_PORT=7108
      - CLUSTER_DATA_BIND_PORT=7109
      - CLUSTER_JOIN=node1:7100
    networks:
      default:
        ipv4_address: 172.19.0.14
    depends_on:
      - node4

  node6:
    hostname: node6
    init: true
    command: --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    restart: on-failure:0
    volumes:
      - /mnt/sdb1/data/weaviate_node_6:/var/lib/weaviate
    env_file:
      - .env_weaviate
    environment:
      - CLUSTER_HOSTNAME=node6
      - CLUSTER_GOSSIP_BIND_PORT=7110
      - CLUSTER_DATA_BIND_PORT=7111
      - CLUSTER_JOIN=node1:7100
    networks:
      default:
        ipv4_address: 172.19.0.16
    depends_on:
      - node5

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
