services:
  api:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/app
    deploy:
      mode: replicated
      replicas: 10
    depends_on:
      - i2v-neural
      - weaviate
      - mongo
    labels:
      autoheal-app: true
    healthcheck:
      test: curl --fail http://api/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/etc/mongo

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: always
    env_file:
      - .env
    depends_on:
      - i2v-neural
  
  i2v-neural:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    restart: always
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 10
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["compute"]

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal-app
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  weaviate_data:
  mongo_data: