services:
  nginx:
    build:
      context: ./nginx
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
    depends_on:
      - api

  api:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    ports:
      - target: 8080
        published: 8080
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
    #   mode: replicated
    #   replicas: 10
    depends_on:
      - i2v-neural
      - weaviate
      - mongo
      # - autoheal
    labels:
      autoheal-app: true
    healthcheck:
      test: curl --fail http://api:8080/health || exit 1
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/etc/mongo
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    volumes:
      - weaviate_data:/var/lib/weaviate
    env_file:
      - .env
    depends_on:
      - i2v-neural
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
  
  i2v-neural:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 10
      # mode: replicated
      # replicas: 10
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["compute"]

  # autoheal:
  #   restart: always
  #   image: willfarrell/autoheal
  #   environment:
  #     - AUTOHEAL_CONTAINER_LABEL=autoheal-app
  #     - AUTOHEAL_DEFAULT_STOP_TIMEOUT=1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  weaviate_data:
  mongo_data: