services:
  api:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      IMAGE_INFERENCE_API: http://i2v-neural:8080
      # IMAGE_INFERENCE_API: http://87.242.104.141:8181
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: true
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: img2vec-neural
      ENABLE_MODULES: img2vec-neural
      CLUSTER_HOSTNAME: node1
  
  i2v-neural:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    restart: always
    environment:
      ENABLE_CUDA: 1
      CUDA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["compute"]

volumes:
  weaviate_data: