services:
  i2v:
    hostname: i2v
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    restart: always
    environment:
      - MODE=production
      - TZ=Europe/Moscow
      - ENABLE_CUDA=1
    deploy:
      mode: replicated
      replicas: 10
      resources:
        reservations:
          # generic_resources:
          #   - discrete_resource_spec:
          #       kind: NVIDIA-GPU
          #       value: 0
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["compute"]

networks:
  services:
    external: true