services:
  mongo:
    hostname: mongo
    image: mongo
    command: --replSet rs0
    environment:
      - TZ=Europe/Moscow
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - /data/mongo/db:/data/db
      - /data/mongo/configdb:/data/configdb
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  mongo1:
    hostname: mongo1
    image: mongo
    command: --replSet rs0
    environment:
      - TZ=Europe/Moscow
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - /data/mongo1/db:/data/db
      - /data/mongo1/configdb:/data/configdb
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  mongo2:
    hostname: mongo2
    image: mongo
    command: --replSet rs0
    environment:
      - TZ=Europe/Moscow
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - /data/mongo2/db:/data/db
      - /data/mongo2/configdb:/data/configdb
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

networks:
  services:
    external: true