services:
  mongo-express:
    hostname: mongo-express
    image: mongo-express
    ports:
      - target: 8081
        published: 8337
        mode: host
    environment:
      - TZ=Europe/Moscow
      - DEBIAN_FRONTEND=noninteractive
      - ME_CONFIG_MONGODB_SERVER=mongo,mongo1,mongo2
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017,mongo1:27017,mongo2:27017/?replicaSet=rs0
      - ME_CONFIG_BASICAUTH_USERNAME=prod
      - ME_CONFIG_BASICAUTH_PASSWORD=J6qC6jUU3Mms
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

networks:
  services:
    external: true