services:
  nginx:
    hostname: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /services/nginx:/etc/nginx
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

networks:
  services:
    external: true