services:
  nginx:
    hostname: nginx
    image: polywaves/nginx:latest
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      - TZ=Europe/Moscow
    networks:
      - services
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s

networks:
  services:
    external: true