services:
  nginx:
    hostname: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /services/nginx/conf.d:/etc/nginx/conf.d
      - /services/nginx/ssl:/etc/nginx/ssl
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

networks:
  services:
    external: true