services:
  nginx:
    hostname: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /services/nginx/conf.d:/etc/nginx/conf.d
      - /services/nginx/ssl:/etc/nginx/ssl
    networks:
      - services
    deploy:
      mode: global
      restart_policy:
        condition: always
        delay: 5s

networks:
  services:
    external: true