services:
  node1:
    hostname: node1
    command: weaviate --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.3
    volumes:
      - /data/weaviate_node_1:/var/lib/weaviate
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_HOSTNAME=node1
      - CLUSTER_GOSSIP_BIND_PORT=7100
      - CLUSTER_DATA_BIND_PORT=7101
      - IMAGE_INFERENCE_API=http://i2v:8080
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=img2vec-neural
      - ENABLE_MODULES=img2vec-neural
      - ASYNC_INDEXING=true
      - RAFT_BOOTSTRAP_EXPECT=8
      - RAFT_JOIN=node1,node2,node3,node4,node5,node6,node7,node8
      - RAFT_BOOTSTRAP_TIMEOUT=3600

  node2:
    hostname: node2
    command: weaviate --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    volumes:
      - /mnt/sda1/data/weaviate_node_2:/var/lib/weaviate
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_HOSTNAME=node2
      - CLUSTER_GOSSIP_BIND_PORT=7102
      - CLUSTER_DATA_BIND_PORT=7103
      - CLUSTER_JOIN=node1:7100
      - IMAGE_INFERENCE_API=http://i2v:8080
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=img2vec-neural
      - ENABLE_MODULES=img2vec-neural
      - ASYNC_INDEXING=true
      - RAFT_BOOTSTRAP_EXPECT=8
      - RAFT_JOIN=node1,node2,node3,node4,node5,node6,node7,node8
      - RAFT_BOOTSTRAP_TIMEOUT=3600

  node3:
    hostname: node3
    command: weaviate --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    volumes:
      - /mnt/sda1/data/weaviate_node_3:/var/lib/weaviate
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_HOSTNAME=node3
      - CLUSTER_GOSSIP_BIND_PORT=7104
      - CLUSTER_DATA_BIND_PORT=7105
      - CLUSTER_JOIN=node1:7100
      - IMAGE_INFERENCE_API=http://i2v:8080
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=img2vec-neural
      - ENABLE_MODULES=img2vec-neural
      - ASYNC_INDEXING=true
      - RAFT_BOOTSTRAP_EXPECT=8
      - RAFT_JOIN=node1,node2,node3,node4,node5,node6,node7,node8
      - RAFT_BOOTSTRAP_TIMEOUT=3600

  node4:
    hostname: node4
    command: weaviate --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    volumes:
      - /mnt/sdb1/data/weaviate_node_4:/var/lib/weaviate
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_HOSTNAME=node4
      - CLUSTER_GOSSIP_BIND_PORT=7106
      - CLUSTER_DATA_BIND_PORT=7107
      - CLUSTER_JOIN=node1:7100
      - IMAGE_INFERENCE_API=http://i2v:8080
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=img2vec-neural
      - ENABLE_MODULES=img2vec-neural
      - ASYNC_INDEXING=true
      - RAFT_BOOTSTRAP_EXPECT=8
      - RAFT_JOIN=node1,node2,node3,node4,node5,node6,node7,node8
      - RAFT_BOOTSTRAP_TIMEOUT=3600

  node5:
    hostname: node5
    command: weaviate --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    volumes:
      - /mnt/sdb1/data/weaviate_node_5:/var/lib/weaviate
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_HOSTNAME=node5
      - CLUSTER_GOSSIP_BIND_PORT=7108
      - CLUSTER_DATA_BIND_PORT=7109
      - CLUSTER_JOIN=node1:7100
      - IMAGE_INFERENCE_API=http://i2v:8080
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=img2vec-neural
      - ENABLE_MODULES=img2vec-neural
      - ASYNC_INDEXING=true
      - RAFT_BOOTSTRAP_EXPECT=8
      - RAFT_JOIN=node1,node2,node3,node4,node5,node6,node7,node8
      - RAFT_BOOTSTRAP_TIMEOUT=3600

  node6:
    hostname: node6
    command: weaviate --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    volumes:
      - /mnt/sdb1/data/weaviate_node_6:/var/lib/weaviate
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_HOSTNAME=node6
      - CLUSTER_GOSSIP_BIND_PORT=7110
      - CLUSTER_DATA_BIND_PORT=7111
      - CLUSTER_JOIN=node1:7100
      - IMAGE_INFERENCE_API=http://i2v:8080
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=img2vec-neural
      - ENABLE_MODULES=img2vec-neural
      - ASYNC_INDEXING=true
      - RAFT_BOOTSTRAP_EXPECT=8
      - RAFT_JOIN=node1,node2,node3,node4,node5,node6,node7,node8
      - RAFT_BOOTSTRAP_TIMEOUT=3600

  node7:
    hostname: node7
    command: weaviate --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    volumes:
      - /mnt/sdb1/data/weaviate_node_7:/var/lib/weaviate
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_HOSTNAME=node7
      - CLUSTER_GOSSIP_BIND_PORT=7112
      - CLUSTER_DATA_BIND_PORT=7113
      - CLUSTER_JOIN=node1:7100
      - IMAGE_INFERENCE_API=http://i2v:8080
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=img2vec-neural
      - ENABLE_MODULES=img2vec-neural
      - ASYNC_INDEXING=true
      - RAFT_BOOTSTRAP_EXPECT=8
      - RAFT_JOIN=node1,node2,node3,node4,node5,node6,node7,node8
      - RAFT_BOOTSTRAP_TIMEOUT=3600

  node8:
    hostname: node8
    command: weaviate --host 0.0.0.0 --port 8080 --scheme http
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.0
    volumes:
      - /mnt/sdb1/data/weaviate_node_8:/var/lib/weaviate
    networks:
      - services
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_HOSTNAME=node8
      - CLUSTER_GOSSIP_BIND_PORT=7114
      - CLUSTER_DATA_BIND_PORT=7115
      - CLUSTER_JOIN=node1:7100
      - IMAGE_INFERENCE_API=http://i2v:8080
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=img2vec-neural
      - ENABLE_MODULES=img2vec-neural
      - ASYNC_INDEXING=true
      - RAFT_BOOTSTRAP_EXPECT=8
      - RAFT_JOIN=node1,node2,node3,node4,node5,node6,node7,node8
      - RAFT_BOOTSTRAP_TIMEOUT=3600

networks:
  services:
    external: true